# Generated by Django 5.1.2 on 2024-11-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Chưa hoàn thành'), ('pending', 'Chờ xác nhận'), ('shipping', 'Chờ giao hàng'), ('completed', 'Đã hoàn thành')], default='cart', max_length=10),
        ),
    ]
