# Generated by Django 5.1.2 on 2024-12-02 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_shippingaddress_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
